@@ -22,12 +22,13 @@ jobs:
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
          
    # Make directory to upload the test results
      - name: Make Directory for results
        run: mkdir -p testResults

      - name: Run API Tests
        run: newman run tau/Lesson4/Restful Booker BVT.postman_collection.json -e tau/Lesson4/Production.postman_environment.json
    

    # Upload the contents of Test Results directory to workspace
